apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-frontend
  namespace: churn-prediction
  labels:
    app: churn-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-frontend
  template:
    metadata:
      labels:
        app: churn-frontend
    spec:
      containers:
      - name: churn-frontend
        image: ghcr.io/your-username/churn-prediction-mlops/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://churn-api-service"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: churn-frontend-service
  namespace: churn-prediction
spec:
  selector:
    app: churn-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP 